CentOS 8 glibc-rh1638523-1.patch: This patch backports the support/ directory as of the upstream commit
This patch backports the support/ directory as of the upstream commit
below.  (It does not include the required Makefile changes to enable
test-in-container builds.)

commit 00c86a37d1b63044e3169d1f2ebec23447c73f79
Author: Adhemerval Zanella <adhemerval.zanella@linaro.org>
Date:   Wed Nov 7 11:09:02 2018 -0200

    support: Fix printf format for TEST_COMPARE_STRING

    Fix the following on 32 bits targets:

    support_test_compare_string.c: In function ‘support_test_compare_string’:
    support_test_compare_string.c:80:37: error: format ‘%lu’ expects argument of
    type ‘long unsigned int’, but argument 2 has type ‘size_t’ {aka ‘unsigned int’}
    [-Werror=format=]
             printf ("  string length: %lu bytes\n", left_length);
                                       ~~^           ~~~~~~~~~~~
                                       %u
    Checked on arm-linux-gnueabihf.

            * support/support_test_compare_string.c
            (support_test_compare_string): Fix printf format.