CentOS 8 glibc-rh1691528-2.patch: Fix parentheses error in iconvconfig.c and ld-collate.c [BZ #24372]
commit 5abcddd7949270998c6e8d99fdbbba821b664f8b
Author: Gabriel F. T. Gomes <gabriel@inconstante.eti.br>
Date:   Thu Mar 21 17:24:30 2019 -0300

    Fix parentheses error in iconvconfig.c and ld-collate.c [BZ #24372]

    When -Werror=parentheses is in use, iconvconfig.c builds fail with:

      iconvconfig.c: In function ‘write_output’:
      iconvconfig.c:1084:34: error: suggest parentheses around ‘+’ inside ‘>>’ [-Werror=parentheses]
         hash_size = next_prime (nnames + nnames >> 1);
                                 ~~~~~~~^~~~~~~~

    This patch adds parentheses to the expression.  Not where suggested by
    the compiler warning, but where it produces the expected result, i.e.:
    where it has the effect of multiplying nnames by 1.5.

    Likewise for elem_size in ld-collate.c.

    Tested for powerpc64le.

    Reviewed-by: Carlos O'Donell <carlos@redhat.com>